---
development:
  DB_FILENAME: 'app/infrastructure/database/local/dev.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  # Application
  APP_HOST: http://localhost:9000

test:
  DB_FILENAME: 'app/infrastructure/database/local/test.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

production:
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  # Application
  APP_HOST: http://url.to.app
  SESSION_SECRET: <some secret>